# generated by datamodel-codegen:
#   filename:  discovery_v1.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict


class FormDataParameter(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    content_type: dict[str, str] | None = None
    """
    Map of different versions of the content type response
    """
    description: str | None = None
    """
    Parameter description
    """
    name: str
    """
    Parameter name
    """
    type: Literal['string', 'number', 'boolean', 'integer', 'array', 'file', 'object']


class ResourceParameter(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    default: str | None = None
    """
    The default value of the parameter
    """
    description: str | None = None
    """
    URI pointing to a resource
    """
    name: str
    """
    Substitution name in the URI template
    """
    required: bool | None = False
    type: Literal['string']


class UriParameter(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    default: Any | None = None
    """
    The default value of the parameter
    """
    description: str | None = None
    """
    Parameter description
    """
    enum: list[str] | None = None
    name: str
    """
    Parameter name
    """
    type: Literal['string', 'number', 'boolean', 'integer', 'array', 'file', 'object']


class Resources(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    accept: dict[str, str] | None = None
    """
    Map of different versions of the accept content
    """
    authentication: list[Literal['auth_header_primary', 'ticket', 'unauthenticated', 'auth_service_token']]
    content_type: dict[str, str] | None = None
    """
    Map of different versions of the content type response
    """
    form_data_parameters: list[FormDataParameter] | None = None
    """
    List of the various allowable form data parameters
    """
    http_method: Literal['GET', 'PUT', 'POST', 'PATCH', 'DELETE', 'HEAD']
    """
    The HTTP method used for this call
    """
    resource_parameter: ResourceParameter | None = None
    """
    If this is method is on an individual resources, the resource_parameter identifies the URI template parameter to substitute
    """
    uri: str
    """
    [URI template](https://tools.ietf.org/html/rfc6570) for this call.  Aplications must use a template library to expand any path or query parameters.
    """
    uri_parameters: list[UriParameter] | None = None
    """
    If there are parameters in the URI path or in the query string, this identifies all the required variables.
    """


class Templates(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    ans_uri: str | None = None
    asset_uri: str | None = None
    commenting_uri: str | None = None
    folder_uri: str | None = None
    review_uri: str | None = None
    search_uri: str | None = None
    search_uri_primary: str | None = None
    search_uri_secondary: str | None = None
    search_uri_v2: str | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    expiry: int
    """
    Unix timestamp (UTC) which indicates the expiration date of the current URLs. Users of DCAPI are expected to refresh their URLs before this expiration. Once expired, URLS will return 404 errors.
    """
    resources: dict[str, dict[str, Resources]]
    """
    All the resource objects in this API
    """
    templates: Templates | None = None
    """
    URI templates to convert ids to uris in client code.
    """
    user_uri: str | None = None
    """
    The base URI to use for queries to retrieve user account information for the current authenticated user.
    """
