[project]
dynamic = ["version"]
name = "pydcapi"
description = "Unofficial Python library for Adobe Document Cloud"
authors = [
    { name = "Max Kuznetsov", email = "maks.kuznetsov@gmail.com" }
]
dependencies = [
    "httpx2>=2.1.0",
    "uritemplate>=3.0.1",
    "pydantic>=2.0",
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed",
]

[project.urls]
GitHub = "https://github.com/mkuznets/pydcapi"

[dependency-groups]
dev = [
    "ruff>=0.12",
    "mypy>=1.17",
    "pytest>=8.3",
    "python-dotenv>=1.1",
]
codegen = [
    "datamodel-code-generator>=0.80",
    "black>=26",
    "isort>=8",
    "autoflake>=2.4",
    "jinja2>=3.1",
    "uritemplate>=4.1",
    "httpx2>=2.1.0",
    "python-dotenv>=1.1",
]

[build-system]
requires = ["hatchling>=1.27", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
raw-options = { local_scheme = "no-local-version" }

[tool.hatch.build.targets.wheel]
packages = ["src/pydcapi"]

[tool.hatch.build.targets.sdist]
only-include = ["src/pydcapi"]
exclude = [".gitignore"]

[tool.ruff]
exclude = ["src/pydcapi/models", "src/pydcapi/resources"]
line-length = 256

[tool.ruff.format]
line-ending = "lf"
quote-style = "double"

[tool.ruff.lint]
select = ["F", "E", "W", "N"]
ignore = [
    "E501", # line length violations
    "F722", # syntax error in forward annotation (false positives in models)
]

[tool.mypy]
disallow_untyped_defs = true
files = ["src/pydcapi", "tests", "codegen"]
exclude = ["src/pydcapi/models"]  # TODO: reenable when all upstream issues are fixed

[[tool.mypy.overrides]]
module = ["pydcapi.models.*"]
disable_error_code = ["valid-type"] # caused by con* types in models. Can be fixed by --field-constraints

[[tool.mypy.overrides]]
module = ["autoflake"]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyright]
venvPath = "."
venv = ".venv"
strict = ["**"]
include = ["src/pydcapi"]
exclude = ["src/pydcapi/models"]
