# generated by datamodel-codegen:
#   filename:  folder_metadata_field_v1.json

from __future__ import annotations

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    created: AwareDatetime | None = None
    """
    The creation date of the folder.
    """
    custom_tags: list[str] | None = None
    """
    An array of custom tags for client application use.
    """
    favorite: bool | None = None
    """
    True if the user has marked this folder a favorite.
    """
    folder_id: str | None = None
    """
    The folder id (in URN form).  Use the "folder_uri" uri template in the "templates" section of the discovery info to transform to a folder uri.
    """
    modified: AwareDatetime | None = None
    """
    The modification date of the folder.
    """
    name: str | None = None
    """
    Name of the folder.
    """
    parent_id: str | None = None
    """
    Folder id (in URN form) of the parent folder of this folder. If there is no parent (e.g. for a transient folder), this value is not present.
    """
    parent_uri: AnyUrl | None = None
    """
    URI of the parent folder of this folder.  If there is no parent (e.g. for a transient folder), this value is not present.
    """
    source: str | None = None
    """
    Where the folder resides.  Currently either "native" or "creative_cloud"
    """
    starred: bool | None = None
    """
    True if the user has starred this folder.
    """
    tags: list[str] | None = None
    """
    An array of tags.
    """
    uri: AnyUrl | None = None
    """
    URI representing the folder
    """
