# generated by datamodel-codegen:
#   filename:  connector_link_parameters_v1.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    code: str
    """
    Authorization code recieved after OAuth URL redirection.
    """
    connectorData: str | None = None
    """
    Stringified JSON data representing connector preferences to be stored in db.
    """
    connectorType: Literal['Teams', 'OneDrive', 'SharePoint', 'GDrive', 'Box', 'DropBox']
    """
    Identifier for Connector class.
    """
