# generated by datamodel-codegen:
#   filename:  source_options_v1.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel


class Model1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    export_uri: str
    """
    Export URI needed for asset export operation. The URI is specific to the destination cloud for assets from origin cloud. Export destination and import origin may be the same in most cases.
    """


class Model(RootModel[dict[str, dict[str, Model1]]]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: dict[str, dict[str, Model1]]
