# generated by datamodel-codegen:
#   filename:  system_log_parameters_v1.json

from __future__ import annotations

from typing import Dict, Literal

from pydantic import BaseModel, ConfigDict, RootModel, constr


class ModelItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, str],
    }
    level: Literal['debug', 'info', 'warn', 'error']
    """
    Log level: debug, info, warn, error.
    """
    message: constr(max_length=2048)
    """
    Message to add to system log.
    """


class Model1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, str],
    }
    level: Literal['debug', 'info', 'warn', 'error']
    """
    Log level: debug, info, warn, error.
    """
    message: constr(max_length=2048)
    """
    Message to add to system log.
    """


class Model(RootModel[list[ModelItem] | Model1]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: list[ModelItem] | Model1
