# generated by datamodel-codegen:
#   filename:  asset_tag_sensei_v1.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ClassificationEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    field_comment: str | None = Field(None, alias='_comment')
    class_label: str | None = None
    score: float | None = None


class ClassificationItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    classification_entries: list[ClassificationEntry] | None = None


class CoordListItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    x: float | None = None
    y: float | None = None


class Polygon(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    coordList: list[CoordListItem] | None = None


class Location(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    polygon: Polygon | None = None


class MetaInfo(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    page_number: float | None = None
    type: str | None = None


class ResponseItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    field_comment: str | None = Field(None, alias='_comment')
    classification: list[ClassificationItem] | None = None
    location: Location | None = None
    meta_info: MetaInfo | None = None


class Result(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    response: list[ResponseItem] | None = None
    response_type: str | None = None
    """
    ANNOTATION
    """


class CasResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    analyzer_id: str | None = None
    """
    Unique service ID, also known as Analyzer ID
    """
    result: Result | None = None
    status: int | None = None
    """
    Status code for the response
    """


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    cas_responses: list[CasResponse] | None = None
    content_id: str | None = None
    """
    A string that identifies the request; if the request included the content_id field, the response will have that value as well.  Otherwise, it will be the URL or file name of the input image
    """
    error: list[dict[str, Any]] | None = None
    status: int | None = None
    """
    HTTP response status code
    """
