# generated by datamodel-codegen:
#   filename:  move_op_params_v1.json

from __future__ import annotations

from typing import Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, constr


class Source(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    object_uri: AnyUrl | None = None
    """
    The uri of object (asset or folder) to move.
    """
    object_uris: list[AnyUrl] | None = Field(None, max_length=200, min_length=1)
    """
    An array of uris of assets and/or folders to move.
    """


class Target(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    name: constr(min_length=1) | None = None
    """
    If present, the new name for the object.
    """
    parent_uri: AnyUrl | None = None
    """
    If present, the uri of the folder to move this object into.
    """


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    on_dup_name: Literal['error', 'auto_rename'] | None = 'error'
    """
    How to handle a duplicate name.
    """
    source: Source
    """
    The thing to move.
    """
    target: Target
    """
    Where to move it to.
    """
