# generated by datamodel-codegen:
#   filename:  exportnotedoc_parameters_v1.json

from __future__ import annotations

from typing import Literal, Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, constr


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    asset_uri: AnyUrl
    """
    URI identifying the Asset.
    """
    format: Optional[Literal['docx']] = 'docx'
    """
    The exportnotedoc format.
    """
    name: constr(min_length=1)
    """
    Name of the new asset. Duplicate asset name behavior can be set by on_dup_policy.
    """
    on_dup_name: Optional[Literal['error', 'auto_rename', 'overwrite']] = 'auto_rename'
    """
    How to handle a duplicate name conflict in target collection for output file.
    """
    parent_uri: Optional[AnyUrl] = None
    """
    The uri of folder to put the asset in. If not specified, the default depends on the operation. Conversions will be placed in the same folder as the source asset.
    """
    persistence: Optional[Literal['transient', 'permanent']] = 'transient'
    """
    Asset storage aspect as short-term transient vs. long-term permanent. "transient" creates an asset that will be available for several hours before being garbage collected and deleted. For operations that convert and download immediately, "transient" is the appropriate choice.
    """
