# generated by datamodel-codegen:
#   filename:  createppt_from_html_parameters_v1.json

from __future__ import annotations

from typing import Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, constr


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    asset_uri: AnyUrl
    """
    Asset URI identifying the HTML file to convert to PowerPoint. Must be an ACP (Platform) asset.
    """
    name: constr(min_length=1)
    """
    Name of the output PPTX asset (e.g. presentation.pptx). Duplicate name behaviour is controlled by on_dup_name.
    """
    on_dup_name: Literal['error', 'auto_rename', 'overwrite'] | None = 'auto_rename'
    """
    How to handle a duplicate name conflict for the output file.
    """
    parent_uri: AnyUrl | None = None
    """
    The uri of folder to put the asset in.  This parameter is relevant only for permanent assets.  If not specified, the default depends on the operation.  Conversions will be placed in the same folder as the source asset.
    """
    persistence: Literal['transient', 'permanent'] | None = 'transient'
    """
    Asset storage aspect as short-term transient vs. long-term permanent. "transient" creates an asset that will be available for several hours before being garbage collected and deleted.  For operations that convert and download immediately, "transient" is the appropriate choice
    """
