# generated by datamodel-codegen:
#   filename:  connector_info_v1.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, constr


class Connector(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    accessToken: str | None = None
    """
    External cloud linked account access token.
    """
    cloudUserId: str | None = None
    """
    External cloud linked account user id.
    """
    connectedAt: float | None = None
    """
    External cloud account connected time.
    """
    connectorData: str | None = None
    """
    Stringified JSON data representing connector preferences to be stored in db.
    """
    connectorId: constr(min_length=1)
    """
    GUID for uniquely identifying each external cloud account linked or ready to be linked.
    """
    connectorType: Literal[
        'Teams', 'OneDrive', 'SharePoint', 'GDrive', 'Box', 'DropBox'
    ]
    """
    Identifier for Connector class.
    """
    createdAt: float
    """
    Connector Info creation time.
    """
    expiresIn: float | None = None
    """
    It represents remaining validity(in seconds) of the access token in connector Info.
    """
    proxyToken: str | None = None
    """
    Proxy token linked to external cloud connector.
    """
    status: Literal['ACTIVE', 'EXPIRED']
    """
    Identifier for the Connector Info state.
    """


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    connector: Connector
    """
    Represents Connector Info details.
    """
