# generated by datamodel-codegen:
#   filename:  user_limits_acrobat_v1.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    acrobat_desktop_mode: Optional[str] = None
    """
    Indicates whether the user is entitled to Acrobat Lite GenAI.
    """
    acrobat_pro: bool
    """
    Indicates whether the user is entitled to download/install Acrobat Pro.
    """
    acrobat_std: bool
    """
    Indicates whether the user is entitled to download/install Acrobat Standard.
    """
