# generated by datamodel-codegen:
#   filename:  user_prefs_v1.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, constr


class Acroprefs(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    prefsync_enabled: bool | None = None


class DcConsent(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    latest_version: str | None = Field(None, alias='latest version')
    """
    version of the latest consent needed
    """
    status: bool | None = None
    """
    indicates the current status of user consent
    """
    version: str | None = None
    """
    version of the consent data
    """


class Genai(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    dc_consent: DcConsent | None = None
    """
    provides essential information about user consent
    """


class Common(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    acroprefs: Acroprefs | None = None
    """
    user preference to sync his acrobat  preferences
    """
    genai: Genai | None = None
    """
    user preference related to genAI feature
    """
    lastToolUsed: str | None = None
    """
    last tool used by user
    """
    sync_favorite_files: bool | None = None
    """
    users pin to cloud preferences
    """


class Fte(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    launch_count: float | None = 0
    welcome_dialog_dismissed: bool | None = False


class Dcweb(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    fte: Fte | None = None
    """
    First Time Experience Tracking
    """


class Fillsign(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    ac_s: Literal[0, 1] | None = 1
    """
    user  preference for auto complete suggestions
    """
    disableFlattenOnSaveDialog: bool | None = False
    """
    user preference for showing warning for flatten on save
    """


class RecentAssets(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    since: (
        constr(
            pattern=r'([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z?|\$\{systemtime_rfc3339\})'
        )
        | None
    ) = None
    """
    The last time the users recent assets list was cleared, represented in UTC formatted to RFC3339. Clients can also pass a special value `${systemtime_rfc3339}` which will use the current time. If recents have not been cleared `since` may be missing.
    """


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    acrobat: dict[str, Any] | None = None
    """
    DC Acrobat Preferences shared across different machines
    """
    common: Common | None = None
    """
    DC Common Preferences across clients
    """
    dcweb: Dcweb | None = None
    """
    DC Web common preferences
    """
    fillsign: Fillsign | None = None
    """
    DC Fillsign Preferences across clients
    """
    recent_assets: RecentAssets | None = None
    """
    Last time recent assets was cleared
    """
    recent_assets_timestamp: (
        constr(
            pattern=r'([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z?|^$|\$\{systemtime_rfc3339\})'
        )
        | None
    ) = ''
    """
    The last time the users recent assets list was cleared, represented in UTC formatted to RFC3339. If the value is an empty string recent assets may not have been set yet. Clients can pass a special value `${systemtime_rfc3339}` which will use the current time or an empty string to clear the recent assets. Example: 2018-01-01T12:00:00Z
    """
