# generated by datamodel-codegen:
#   filename:  createpdf_options_v1.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FileFormats(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    mime_type: str
    """
    The mime type corresponding to this file extension.
    """


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    file_formats: list[dict[str, FileFormats]] | None = None
    """
    File Extensions and mime types. In the future, this list may be extended without a change in version.
    """
