# generated by datamodel-codegen:
#   filename:  redactpdf_parameters_v1.json

from __future__ import annotations

from typing import Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, constr


class Coordinate(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    bottom: float
    """
    Bottom coordinate of the redaction rectangle.
    """
    left: float
    """
    Left coordinate of the redaction rectangle.
    """
    right: float
    """
    Right coordinate of the redaction rectangle.
    """
    top: float
    """
    Top coordinate of the redaction rectangle.
    """


class RedactLocation(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    coordinates: list[Coordinate]
    """
    Bounding box rectangles defining the redaction area on the page.
    """
    pageNumber: int
    """
    1-based page number where the redaction is applied.
    """


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    asset_uri: AnyUrl
    """
    URI identifying the PDF asset to redact.
    """
    format: Literal['pdf'] | None = 'pdf'
    """
    Output format of the redacted document.
    """
    name: constr(min_length=1)
    """
    Name of the output asset.
    """
    persistence: Literal['transient', 'permanent'] | None = 'transient'
    """
    Asset storage aspect as short-term transient vs. long-term permanent. "transient" creates an asset that will be available for several hours before being garbage collected and deleted.  For operations that convert and download immediately, "transient" is the appropriate choice
    """
    redact_locations: list[RedactLocation] | None = None
    """
    List of page locations to redact.
    """
    sanitize: bool | None = False
    """
    Whether to sanitize the PDF document metadata.
    """
