# generated by datamodel-codegen:
#   filename:  asset_metadata_field_patch_v1.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class CustomTag(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    op: Literal['insert', 'delete'] | None = None
    """
    Wether to insert or delete the specified value from the tags array.
    """
    value: str | None = None
    """
    A short user defined tag value to insert or delete.
    """


class Tag(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    op: Literal['insert', 'delete'] | None = None
    """
    Wether to insert or delete the specified value from the tags array.
    """
    value: str | None = None
    """
    A short user defined tag value to insert or delete.
    """


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    custom_tags: list[CustomTag] | None = Field(None, max_length=10, min_length=1)
    """
    An array of patch instructions to modify the tags metadata field.
    """
    tags: list[Tag] | None = Field(None, max_length=10, min_length=1)
    """
    An array of patch instructions to modify the tags metadata field.
    """
