# generated by datamodel-codegen:
#   filename:  user_cohorts_v1.json

from __future__ import annotations

from pydantic import ConfigDict, RootModel


class Model(RootModel[dict[str, str]]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: dict[str, str]
