# generated by datamodel-codegen:
#   filename:  copy_op_params_v1.json

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, ConfigDict, constr


class Source(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    asset_uri: AnyUrl
    """
    The uri of the asset to copy.
    """


class Target(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    name: constr(min_length=1) | None = None
    """
    If present, the new name for the asset.
    """
    parent_uri: AnyUrl | None = None
    """
    If present, the uri of the folder to copy this asset into.
    """


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    source: Source
    """
    The thing to copy.
    """
    target: Target
    """
    Where to copy it to.
    """
